### ISSUE TITLE
[BUG] Can't run the Language Server

### ISSUE THREAD

**Issue by pr1metine** [processing-language-server/LS4P#6]
It looks like I am unable to get your server up and running @SyamSundarKirubakaran 😢 .

![image](https://user-images.githubusercontent.com/50841263/82121670-1bc16c80-978f-11ea-9245-b403844518d3.png)
![image](https://user-images.githubusercontent.com/50841263/82121711-67741600-978f-11ea-82e6-708ead3c7a49.png)

I tried Windows, WSL and Ubuntu 20.04 via Hyper-V with no success. Could you please confirm that your server is working as intended?

**Comment by pr1metine** [comment]
![image](https://user-images.githubusercontent.com/50841263/82121849-62fc2d00-9790-11ea-8438-b080bddf55df.png)

A screenshot for WSL for good measures.

Btw, I am running nodejs 12.16.3 and either Oracle JDK 8u202, 8u251 or OpenJDK 8 on all of my machines.

**Comment by SyamSundarKirubakaran** [comment]
Hey @pr1metine The Language Server is build using shell commands for run-time code intelli-sense I'm pretty sure running in windows will not work. Not tried it on Ubuntu VM but can you try re-running the build scripts with `sudo` after clearing the project node_modules both in parent and it's child directories.

**Comment by pr1metine** [comment]
Hello @SyamSundarKirubakaran ,
yeah you are right about Windows. I merely ran `npm i` and did my checks. That said, I attempted to run `initserver.sh` and `reinitserver.sh` with root privileges on WSL and the Ubuntu VM. Still I have not been successful and the same errors can be seen as in the screenshots. Note that the following output is made with WSL 2.

```sh
$ sudo -s
# java -version
openjdk version "1.8.0_252"
OpenJDK Runtime Environment (build 1.8.0_252-8u252-b09-1~18.04-b09)
OpenJDK 64-Bit Server VM (build 25.252-b09, mixed mode)
# echo $CLASSPATH
/opt/processing-3.5.4/core/library/core.jar
# uname -a
Linux Vierzehnhundert 4.19.84-microsoft-standard #1 SMP Wed Nov 13 11:44:37 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

When I try running `reinitserver.sh` (for full output see [this gist](https://gist.github.com/pr1metine/dcbaae2d95c9573d839a16bfb418f1c0#file-terminal-log)):
```sh
# sh ./reinitserver.sh
Performing Server Cleanup...
rm: cannot remove './node_modules': No such file or directory
rm: cannot remove './node_modules': No such file or directory
Server Cleanup successful.!
Installing required node modules...
npm WARN lifecycle processing-lsp@1.0.0~postinstall: cannot run in wd processing-lsp@1.0.0 cd client && npm install && cd ../server && npm install && cd .. (wd=/home/pr1metine/projects/LS4P)
added 42 packages from 49 contributors and audited 42 packages in 1.427s
found 1 low severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details
Installation successful.!
[...]
```

When executing `npm i` in `server/` and checking the error log (see [gist](https://gist.github.com/pr1metine/dcbaae2d95c9573d839a16bfb418f1c0#file-2020-05-17t07_11_08_678z-debug-log)):
```log
[...]
592 silly install java@0.11.0
593 info lifecycle java@0.11.0~install: java@0.11.0
594 verbose lifecycle java@0.11.0~install: unsafe-perm in lifecycle false
595 verbose lifecycle java@0.11.0~install: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/pr1metine/projects/LS4P/server/node_modules/java/node_modules/.bin:/home/pr1metine/projects/LS4P/server/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
596 verbose lifecycle java@0.11.0~install: CWD: /home/pr1metine/projects/LS4P/server/node_modules/java
597 silly lifecycle java@0.11.0~install: Args: [ '-c', 'node-gyp rebuild' ]
598 silly lifecycle java@0.11.0~install: Returned: code: 1  signal: null
599 info lifecycle java@0.11.0~install: Failed to exec install script
600 timing action:install Completed in 1559ms
601 verbose unlock done using /home/pr1metine/.npm/_locks/staging-5c826cc467e78338.lock for /home/pr1metine/projects/LS4P/server/node_modules/.staging
602 timing stage:rollbackFailedOptional Completed in 159ms
603 timing stage:runTopLevelLifecycles Completed in 2675ms
604 silly saveTree processing-lsp-client@0.0.1
604 silly saveTree ├─┬ java-class-tools@1.3.1
604 silly saveTree │ └─┬ bytebuffer@5.0.1
604 silly saveTree │   └── long@3.2.0
604 silly saveTree ├─┬ java@0.11.0
604 silly saveTree │ ├─┬ async@2.6.1
604 silly saveTree │ │ └── lodash@4.17.11
604 silly saveTree │ ├─┬ find-java-home@0.2.0
604 silly saveTree │ │ ├── which@1.0.9
604 silly saveTree │ │ └── winreg@1.2.4
604 silly saveTree │ ├─┬ glob@7.1.3
604 silly saveTree │ │ ├── fs.realpath@1.0.0
604 silly saveTree │ │ ├─┬ inflight@1.0.6
604 silly saveTree │ │ │ ├─┬ once@1.4.0
604 silly saveTree │ │ │ │ └── wrappy@1.0.2
604 silly saveTree │ │ │ └── wrappy@1.0.2
604 silly saveTree │ │ ├── inherits@2.0.4
604 silly saveTree │ │ ├─┬ minimatch@3.0.4
604 silly saveTree │ │ │ └─┬ brace-expansion@1.1.11
604 silly saveTree │ │ │   ├── balanced-match@1.0.0
604 silly saveTree │ │ │   └── concat-map@0.0.1
604 silly saveTree │ │ ├── once@1.4.0
604 silly saveTree │ │ └── path-is-absolute@1.0.1
604 silly saveTree │ ├── lodash@4.17.11
604 silly saveTree │ └── nan@2.11.1
604 silly saveTree └─┬ vscode-languageserver@4.1.3
604 silly saveTree   ├─┬ vscode-languageserver-protocol@3.7.2
604 silly saveTree   │ ├── vscode-jsonrpc@3.6.2
604 silly saveTree   │ └── vscode-languageserver-types@3.7.2
604 silly saveTree   └── vscode-uri@1.0.3
605 verbose stack Error: java@0.11.0 install: `node-gyp rebuild`
605 verbose stack Exit status 1
605 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
605 verbose stack     at EventEmitter.emit (events.js:310:20)
605 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
605 verbose stack     at ChildProcess.emit (events.js:310:20)
605 verbose stack     at maybeClose (internal/child_process.js:1021:16)
605 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
606 verbose pkgid java@0.11.0
607 verbose cwd /home/pr1metine/projects/LS4P/server
608 verbose Linux 4.19.84-microsoft-standard
609 verbose argv "/usr/bin/node" "/usr/bin/npm" "i"
610 verbose node v12.16.3
611 verbose npm  v6.14.4
612 error code ELIFECYCLE
613 error errno 1
614 error java@0.11.0 install: `node-gyp rebuild`
614 error Exit status 1
615 error Failed at the java@0.11.0 install script.
615 error This is probably not a problem with npm. There is likely additional logging output above.
616 verbose exit [ 1, true ]
```

Maybe there is something wrong with the Java npm package or with my Java configuration in general. Could you walkthrough the whole process of setting up the server? Could you also state all prerequisites and dependencies?

**Comment by pr1metine** [comment]
> Open LS4P in VSCode and perform Terminal -> Run Build Task... from the Menu.

Running this results in the following output:
```
[11:11:02 AM] Starting compilation in watch mode...

client/src/extension.ts:2:25 - error TS2307: Cannot find module 'vscode'.

2 import * as vscode from 'vscode';
                          ~~~~~~~~

client/src/extension.ts:10:8 - error TS2307: Cannot find module 'vscode-languageclient'.

10 } from 'vscode-languageclient';
          ~~~~~~~~~~~~~~~~~~~~~~~

client/src/extension.ts:71:31 - error TS2304: Cannot find name 'Thenable'.

71 export function deactivate(): Thenable<void> | undefined {
                                 ~~~~~~~~

server/src/hover.ts:1:22 - error TS2307: Cannot find module 'vscode-languageserver'.

1 import * as lsp from 'vscode-languageserver'
                       ~~~~~~~~~~~~~~~~~~~~~~~

server/src/hover.ts:4:37 - error TS2307: Cannot find module 'vscode-languageserver'.

4 import { Hover, MarkedString } from 'vscode-languageserver';
                                      ~~~~~~~~~~~~~~~~~~~~~~~

server/src/definition.ts:7:28 - error TS2307: Cannot find module 'vscode-languageserver'.

7 import { Definition } from 'vscode-languageserver'
                             ~~~~~~~~~~~~~~~~~~~~~~~

server/src/lens.ts:1:42 - error TS2307: Cannot find module 'vscode-languageserver'.

1 import { CodeLens, CodeLensParams } from 'vscode-languageserver'
                                           ~~~~~~~~~~~~~~~~~~~~~~~

server/src/references.ts:1:43 - error TS2307: Cannot find module 'vscode-languageserver'.

1 import { Location, ReferenceParams } from 'vscode-languageserver'
                                            ~~~~~~~~~~~~~~~~~~~~~~~

server/src/server.ts:18:8 - error TS2307: Cannot find module 'vscode-languageserver'.

18 } from 'vscode-languageserver';
          ~~~~~~~~~~~~~~~~~~~~~~~

server/src/server.ts:76:52 - error TS7006: Parameter '_event' implicitly has an 'any' type.

76      connection.workspace.onDidChangeWorkspaceFolders(_event => {
                                                         ~~~~~~

server/src/server.ts:89:35 - error TS2304: Cannot find name 'Thenable'.

89 let documentSettings: Map<string, Thenable<ExampleSettings>> = new Map();
                                     ~~~~~~~~

server/src/server.ts:91:37 - error TS7006: Parameter 'change' implicitly has an 'any' type.

91 connection.onDidChangeConfiguration(change => {
                                       ~~~~~~

server/src/server.ts:104:56 - error TS2304: Cannot find name 'Thenable'.

104 export function getDocumentSettings(resource: string): Thenable<ExampleSettings> {
                                                           ~~~~~~~~

server/src/server.ts:119:21 - error TS7006: Parameter 'event' implicitly has an 'any' type.

119 documents.onDidOpen(event => {
                        ~~~~~

server/src/server.ts:126:22 - error TS7006: Parameter 'e' implicitly has an 'any' type.

126 documents.onDidClose(e => {
                         ~

server/src/server.ts:132:30 - error TS7006: Parameter 'change' implicitly has an 'any' type.

132 documents.onDidChangeContent(change => {
                                 ~~~~~~

server/src/server.ts:142:36 - error TS7006: Parameter '_change' implicitly has an 'any' type.

142 connection.onDidChangeWatchedFiles(_change => {
                                       ~~~~~~~

server/src/diagnostics.ts:5:8 - error TS2307: Cannot find module 'vscode-languageserver'.

5 } from 'vscode-languageserver';
         ~~~~~~~~~~~~~~~~~~~~~~~

server/src/parser.ts:4:30 - error TS2307: Cannot find module 'vscode-languageserver'.

4 import { TextDocument } from 'vscode-languageserver';
                               ~~~~~~~~~~~~~~~~~~~~~~~

server/src/preprocessing.ts:1:22 - error TS2307: Cannot find module 'vscode-languageserver'.

1 import * as lsp from 'vscode-languageserver'
                       ~~~~~~~~~~~~~~~~~~~~~~~

server/src/completion.ts:1:22 - error TS2307: Cannot find module 'vscode-languageserver'.

1 import * as lsp from 'vscode-languageserver';
                       ~~~~~~~~~~~~~~~~~~~~~~~

server/src/completion.ts:2:68 - error TS2307: Cannot find module 'vscode-languageserver'.

2 import { CompletionItemKind, CompletionParams, TextDocument } from 'vscode-languageserver';
                                                                     ~~~~~~~~~~~~~~~~~~~~~~~

[11:11:05 AM] Found 22 errors. Watching for file changes.
```

**Comment by SyamSundarKirubakaran** [comment]
I'll give it a spin in my end and I'll let you know if it fails on my end as well.

**Comment by pr1metine** [comment]
So? Did you succeed, @SyamSundarKirubakaran ?

**Comment by SyamSundarKirubakaran** [comment]
Nope, definitely failing. I encountered the same issue with `java` npm package, in addition the `vscode` package (which is a main part of this project) is been deprecated, and migrated to `vscode-test` with it's own `@types`, on performing migration multiple dependent modules are throwing exceptions. Seems like I'll have to refactor/restructure a good amount of code. It's gonna take a while.

In the meantime, If you're really into language servers. I'll suggest you look into https://github.com/microsoft/vscode-extension-samples/tree/master/lsp-sample

<img width="1210" alt="Screenshot 2020-05-31 at 9 24 51 AM" src="https://user-images.githubusercontent.com/26897680/83344408-39acd680-a324-11ea-9d94-5da5f12a02a7.png">

**Comment by pr1metine** [comment]
Godspeed, SyamSundarKirubakaran. Would you mind if I implemented the server with [LSP4J](https://github.com/eclipse/lsp4j)?

**Comment by SyamSundarKirubakaran** [comment]
Sure. I remember looking into LSP4J a year earlier but since I was about to build a Language Server for an Upcoming IDE for Processing with will probably be written in Electron JS. I went with the JS side of implementation. You can try it out with LSP4J as well.!

**Comment by SyamSundarKirubakaran** [comment]
Should be working now.! Just do a clean and rebuild.!
